const tempStoreData = [
  {
    id: "123",
    title: "Eyesore Cinema",
    featuredImage: {
      node: { sourceUrl: "/assets/stores/eyesore.jpg" },
    },
    videoStoreFields: {
      storeName: "Eyesore Cinema",
      streetAddress: "1176 Bloor Street West",
      city: "Toronto",
      stateprovince: "Ontario",
      country: "Canada",
      videoStoreDayParticipant: "true",
      website: "https://eyesorecinema.com",
      instagram: "",
      facebook: "",
    },
  },
  {
    id: "234",
    title: "Scarecrow Video",
    featuredImage: {
      node: { sourceUrl: "/assets/stores/scarecrow.jpg" },
    },
    videoStoreFields: {
      storeName: "Scarecrow Video",
      streetAddress: "5030 Roosevelt Way SE",
      city: "Seattle",
      stateprovince: "Washington",
      country: "USA",
      videoStoreDayParticipant: "true",
      website: "https://scarecrow.com",
      instagram: "",
      facebook: "",
    },
  },
  {
    id: "345",
    title: "20th Century Flicks",
    featuredImage: {
      node: { sourceUrl: "/assets/stores/20c.jpg" },
    },
    videoStoreFields: {
      storeName: "20th Century Flicks Video Shop",
      streetAddress: "19 Christmas Steps",
      city: "Bristol",
      stateprovince: "",
      country: "UK",
      videoStoreDayParticipant: "true",
      website: "https://20thcenturyflicks.co.uk",
      instagram: "",
      facebook: "",
    },
  },
  {
    id: "456",
    title: "Four Star Video",
    featuredImage: {
      node: { sourceUrl: "/assets/stores/4star.jpg" },
    },
    videoStoreFields: {
      storeName: "Four Star Video",
      streetAddress: "459W Gilman Street",
      city: "Madison",
      stateprovince: "Wisconsin",
      country: "USA",
      videoStoreDayParticipant: "true",
      website: "https://fourstarvideorental.com",
      instagram: "",
      facebook: "",
    },
  },
  {
    id: "567",
    title: "Video Strip",
    featuredImage: {
      node: { sourceUrl: "/assets/stores/videostrip.jpg" },
    },
    videoStoreFields: {
      storeName: "The Video Strip",
      streetAddress: "3307 S Archer Avenue",
      city: "Chicago",
      stateprovince: "Illinois",
      country: "USA",
      videoStoreDayParticipant: "true",
      website: "",
      instagram: "",
      facebook: "",
    },
  },
  {
    id: "678",
    title: "The Lobby",
    featuredImage: {
      node: { sourceUrl: "/assets/stores/lobby.jpg" },
    },
    videoStoreFields: {
      storeName: "The Lobby",
      streetAddress: "10815 82 Avenue NW",
      city: "Edmonton",
      stateprovince: "Alberta",
      country: "Canada",
      videoStoreDayParticipant: "true",
      website: "https://www.facebook.com/groups/339360600129",
      instagram: "",
      facebook: "https://www.facebook.com/groups/339360600129",
    },
  },
  {
    id: "789",
    title: "JM Video",
    featuredImage: {
      node: { sourceUrl: "/assets/stores/jmvideo.jpg" },
    },
    videoStoreFields: {
      storeName: "JM Video",
      streetAddress: "121 Avenue Parmentier",
      city: "Paris",
      stateprovince: "",
      country: "France",
      videoStoreDayParticipant: "false",
      website: "https://jmvideo.fr",
      instagram: "",
      facebook: "",
    },
  },
  {
    id: "890",
    title: "Straight to Video",
    featuredImage: {
      node: { sourceUrl: "/assets/stores/straighttovideo.jpg" },
    },
    videoStoreFields: {
      storeName: "Straight To Video",
      streetAddress: "11 King Street",
      city: "Alfreton",
      stateprovince: "Derbyshire",
      country: "UK",
      videoStoreDayParticipant: "false",
      website: "http://www.80svideoshop.co.uk/",
      instagram: "",
      facebook: "",
    },
  },
  {
    id: "987",
    title: "Beyond Video",
    featuredImage: {
      node: { sourceUrl: "assets/stores/beyondvideo.jpg" },
    },
    videoStoreFields: {
      storeName: "Beyond Video",
      streetAddress: "2545 N Howard Street",
      city: "Baltimore",
      stateprovince: "Maryland",
      country: "USA",
      videoStoreDayParticipant: "true",
      website: "https://beyondvideo.org",
      instagram: "",
      facebook: "",
    },
  },
  {
    id: "876",
    title: "Movie Madness",
    featuredImage: {
      node: { sourceUrl: "/assets/stores/moviemadness.jpg" },
    },
    videoStoreFields: {
      storeName: "Movie Madness",
      streetAddress: "4320 SE Belmont Street",
      city: "Portland",
      stateprovince: "Oregon",
      country: "USA",
      videoStoreDayParticipant: "true",
      website: "hhttps://moviemadness.org/",
      instagram: "",
      facebook: "",
    },
  },
  {
    id: "765",
    title: "Vidiots",
    featuredImage: {
      node: { sourceUrl: "/assets/stores/vidiots.jpg" },
    },
    videoStoreFields: {
      storeName: "Vidiots",
      streetAddress: "4884 Eagle Rock Blvd",
      city: "Los Angeles",
      stateprovince: "California",
      country: "USA",
      videoStoreDayParticipant: "true",
      website: "https://vidiotsfoundation.org/",
      instagram: "",
      facebook: "",
    },
  },
  {
    id: "654",
    title: "Videodrome",
    featuredImage: {
      node: { sourceUrl: "/assets/stores/videodrome.jpg" },
    },
    videoStoreFields: {
      storeName: "Videodrome",
      streetAddress: "617 N Highland Avenue NE",
      city: "Atlanta",
      stateprovince: "Georgia",
      country: "USA",
      videoStoreDayParticipant: "true",
      website: "https://videodrome.tv/",
      instagram: "",
      facebook: "",
    },
  },
  {
    id: "543",
    title: "Video Cat",
    featuredImage: {
      node: { sourceUrl: "/assets/stores/videocat.jpg" },
    },
    videoStoreFields: {
      storeName: "Video Cat",
      streetAddress: "3451 Cambie Street",
      city: "Vancouver",
      stateprovince: "BC",
      country: "Canada",
      videoStoreDayParticipant: "true",
      website: "https://www.videocat.ca/",
      instagram: "",
      facebook: "",
    },
  },
  {
    id: "432",
    title: "Traumathek",
    featuredImage: {
      node: { sourceUrl: "/assets/stores/traumathek.jpg" },
    },
    videoStoreFields: {
      storeName: "Traumathek",
      streetAddress: "Engelbertstrasse 45 50674",
      city: "Köln",
      stateprovince: "",
      country: "Germany",
      videoStoreDayParticipant: "true",
      website: "http://www.traumathek.de/",
      instagram: "",
      facebook: "",
    },
  },
  {
    id: "321",
    title: "Snips Movies",
    featuredImage: {
      node: { sourceUrl: "/assets/stores/snips.jpg" },
    },
    videoStoreFields: {
      storeName: "Snips Movies",
      streetAddress: "22 Cross Lane",
      city: "Bebbington",
      stateprovince: "Wirral",
      country: "UK",
      videoStoreDayParticipant: "true",
      website: "https://www.facebook.com/snipsmovieswirral",
      instagram: "",
      facebook: "",
    },
  },
  {
    id: "111",
    title: "C & M Convenience and Movies",
    featuredImage: {
      node: { sourceUrl: "/assets/stores/candmconvenience.jpg" },
    },
    videoStoreFields: {
      storeName: "C & M Convenience and Movies",
      streetAddress: "10054 Grenville Street",
      city: "St. Peters",
      stateprovince: "Nova Scotia",
      country: "Canada",
      videoStoreDayParticipant: "false",
      website: "https://www.facebook.com/CMVIDEOStPeters",
      instagram: "",
      facebook: "",
    },
  },
];

export default tempStoreData;
